- name: Backup web application and upload to S3
  hosts: 3.85.192.207
  remote_user: ubuntu
  become: yes
  vars:
    s3_bucket: dr-fe
    aws_region: us-east-1
    aws_access_key: AKIAVY2PHB5JDHC5JZWP
    aws_secret_key: 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
  tasks:

    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Create a backup of the web application
      command: >
        tar czf /tmp/webapp-backup-{{ ansible_date_time.date }}.tar.gz -C /var/www/html .

    - name: Download AWS CLI installer
      command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI installer
      command: unzip /tmp/awscliv2.zip -d /tmp/

    - name: Install AWS CLI
      command: sudo /tmp/aws/install

    - name: Upload backup to S3
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      command: >
        /usr/local/bin/aws s3 cp /tmp/webapp-backup-{{ ansible_date_time.date }}.tar.gz
        s3://{{ s3_bucket }}/
        --region {{ aws_region }}

    - name: Clean up local backup file
      file:
        path: /tmp/webapp-backup-{{ ansible_date_time.date }}.tar.gz
        state: absent

    - name: Remove AWS CLI installer files
      file:
        path: /tmp/awscliv2.zip
        state: absent
      ignore_errors: yes

    - name: Remove extracted AWS CLI folder
      file:
        path: /tmp/aws
        state: absent
      ignore_errors: yes
