- name: Backup PostgreSQL database and upload to S3
  hosts: 52.87.209.246
  become: yes
  vars:
    db_name: redhatdb
    db_user: redhat
    s3_bucket: ansible.database1
    aws_region: us-east-1
  tasks:

    - name: Create a backup of the PostgreSQL database
      shell: >
        pg_dump -U {{ db_user }} {{ db_name }} | gzip > /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
      environment:
        PGPASSWORD: redhat

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Upload backup to S3
      command: >
        aws s3 cp /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
        s3://{{ s3_bucket }}/
        --region {{ aws_region }}

    - name: Clean up local backup file
      file:
        path: /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
        state: absent
