- name: Backup PostgreSQL database and upload to S3
  hosts: 54.158.142.5
  remote_user: ubuntu
  become: yes
  vars:
    s3_bucket: dr-db
    db_name: redhatdb
    db_user: redhat
    aws_region: us-east-1
    aws_access_key: AKIAVY2PHB5JDHC5JZWP
    aws_secret_key: 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
  tasks:

    - name: Create a backup of the PostgreSQL database
      shell: >
        pg_dump -U {{ db_user }} {{ db_name }} | gzip > /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
      environment:
        PGPASSWORD: redhat

    # - name: Download AWS CLI installer
    #   command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"

    # - name: Unzip AWS CLI installer
    #   command: unzip /tmp/awscliv2.zip -d /tmp/

    # - name: Install AWS CLI
    #   command: sudo /tmp/aws/install

    - name: Upload backup to S3
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      command: >
        aws s3 cp /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
        s3://{{ s3_bucket }}/
        --region {{ aws_region }}

    - name: Clean up local backup file
      file:
        path: /tmp/db-backup-{{ ansible_date_time.date }}.sql.gz
        state: absent
