---
- name: Perform Health Check on App Server
  hosts: all
  tasks:
    - name: Check if the app server is alive
      uri:
        url: "http://143.244.142.40"
        return_content: yes
      register: result
      until: '"alive" in result.content'
      retries: 10
      delay: 1
      ignore_errors: yes

    - name: Print health check result
      debug:
        var: result.content
