---
- name: Perform Health Check on App Server
  hosts: all
  tasks:
    - name: Check if the app server is alive
      uri:
        url: "http://44.202.97.64"
        return_content: yes
      register: result
      until: '"alive" in result.content'
      retries: 3
      delay: 1
      failed_when: result.status is not defined or '"alive" not in result.content'
    #  ignore_errors: yes

    - name: Print health check result
      debug:
        var: result.content
