- name: Restore PostgreSQL database from S3 backup
  hosts: 18.117.124.96
  remote_user: ubuntu
  become: yes
  vars:
    db_name: redhatdb
    db_user: redhat
    db_password: redhat  # Set the password for the 'redhat' user
    s3_bucket: dr-db
    aws_region: us-east-1
    aws_access_key: AKIAVY2PHB5JDHC5JZWP
    aws_secret_key: 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
    backup_date: "{{ ansible_date_time.date }}"
  tasks:

    - name: Install PostgreSQL, gzip, and unzip
      apt:
        name:
          - postgresql
          - postgresql-client
          - gzip
          - unzip
        state: present
        update_cache: yes

    - name: Configure PostgreSQL to allow password authentication for local connections
      lineinfile:
        dest: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer$'
        line: 'local all postgres md5'
      notify: Restart PostgreSQL

    - name: Ensure PostgreSQL is listening on localhost
      lineinfile:
        dest: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = 'localhost'"
      notify: Restart PostgreSQL

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Create database user 'redhat'
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present

    - name: Create database 'redhatdb'
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        encoding: "UTF8"
        state: present

    - name: Grant all privileges on database 'redhatdb' to user 'redhat'
      become_user: postgres
      postgresql_privs:
        db: "{{ db_name }}"
        roles: "{{ db_user }}"
        type: database
        privs: "ALL"

    - name: Download backup from S3
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      command: >
        aws s3 cp s3://{{ s3_bucket }}/db-backup-{{ backup_date }}.sql.gz /tmp/db-backup-{{ backup_date }}.sql.gz
        --region {{ aws_region }}
      register: download_status
      failed_when: download_status.rc != 0

    - name: Restore PostgreSQL database from backup
      shell: >
        gunzip -c /tmp/db-backup-{{ backup_date }}.sql.gz | psql -U postgres -d {{ db_name }}
      environment:
        PGPASSWORD: "{{ db_password }}"
      register: restore_status
      failed_when: restore_status.rc != 0

    - name: Clean up local backup file
      file:
        path: /tmp/db-backup-{{ backup_date }}.sql.gz
        state: absent
      when: download_status.rc == 0 and restore_status.rc == 0

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
