- name: Restore PostgreSQL database from S3 backup
  hosts: 3.15.156.213
  become: yes
  vars:
    db_name: redhatdb
    db_user: redhat
    s3_bucket: ansible.database1
    backup_date: "{{ ansible_date_time.date }}"  # Adjust if needed
  tasks:

    - name: Install PostgreSQL and gzip
      apt:
        name:
          - postgresql
          - postgresql-client
          - gzip
        state: present

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Download backup from S3
      command: >
        aws s3 cp s3://{{ s3_bucket }}/db-backup-{{ backup_date }}.sql.gz /tmp/db-backup-{{ backup_date }}.sql.gz
      register: download_status
      failed_when: download_status.rc != 0

    - name: Restore PostgreSQL database from backup
      shell: >
        gunzip -c /tmp/db-backup-{{ backup_date }}.sql.gz | psql -U {{ db_user }} -d {{ db_name }}
      environment:
        PGPASSWORD: redhat
      register: restore_status
      failed_when: restore_status.rc != 0

    - name: Clean up local backup file
      file:
        path: /tmp/db-backup-{{ backup_date }}.sql.gz
        state: absent
      when: download_status.rc == 0 and restore_status.rc == 0
