- name: Download the latest file from S3 bucket
  hosts: 18.117.124.96
  remote_user: ubuntu
  become: yes
  vars:
    s3_bucket: dr-db
    aws_region: us-east-1
    aws_access_key: AKIAVY2PHB5JDHC5JZWP
    aws_secret_key: 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
  tasks:
    - name: Find the latest file in S3
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      command: >
        aws s3 ls s3://{{ s3_bucket }}/ --region {{ aws_region }} --recursive | sort | tail -n 1 | awk '{print $4}'
      register: latest_file
      changed_when: false

    - name: Download the latest file from S3
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      command: >
        aws s3 cp s3://{{ s3_bucket }}/{{ latest_file.stdout }} /tmp/latest-file --region {{ aws_region }}
      register: download_status
      failed_when: download_status.rc != 0
