---
- name: Restore latest backup from primary site
  hosts: 52.15.98.102
  become: yes
  vars:
    aws_region: us-east-2
    s3_bucket: ansible-backup2
  tasks:

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Get the latest backup file from S3
      command: >
        aws s3 ls s3://{{ s3_bucket }}/ --region {{ aws_region }}
      register: s3_list

    - name: Set the latest backup filename
      set_fact:
        latest_backup: "{{ s3_list.stdout_lines | select('search', 'webapp-backup-') | list | last | regex_replace('.* (webapp-backup-\\S+\\.tar\\.gz)', '\\1') }}"

    - name: Download the latest backup from S3
      command: >
        aws s3 cp s3://{{ s3_bucket }}/{{ latest_backup }} /tmp/{{ latest_backup }} --region {{ aws_region }}

    - name: Extract the backup
      command: >
        tar xzf /tmp/{{ latest_backup }} -C /var/www/html

    - name: Set ownership and permissions
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Clean up local backup file
      file:
        path: /tmp/{{ latest_backup }}
        state: absent
