- name: Install PostgreSQL and restore database from S3
  hosts: 3.15.156.213
  become: yes
  become_method: sudo
  become_user: root
  vars:
    db_name: redhatdb
    db_user: redhat
    s3_bucket: ansible.database
    backup_file: db-backup-{{ ansible_date_time.date }}.sql.gz
    backup_file_path: /{{ backup_file }}  # Updated path
    db_restore_path: /db-backup-{{ ansible_date_time.date }}.sql  # Updated path
    remote_tmp: /root/ansible  # Updated custom temporary directory path
  tasks:

    - name: Ensure temporary directory exists
      file:
        path: "{{ remote_tmp }}"
        state: directory
        mode: '1777'  # Ensure it has appropriate permissions

    - name: Install PostgreSQL, gzip, and utilities
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - awscli
          - gzip
        state: present

    - name: Debug variables
      debug:
        msg: "Backup file path: {{ backup_file_path }}"

    - name: Download database backup from S3
      command: >
        aws s3 cp s3://{{ s3_bucket }}/{{ backup_file }} {{ backup_file_path }}
      register: s3_download
      failed_when: "'404' in s3_download.stderr"
      changed_when: true

    - name: Debug S3 download result
      debug:
        msg: "S3 download command output: {{ s3_download.stdout }}\nError: {{ s3_download.stderr }}"

    - name: Check if backup file exists
      stat:
        path: "{{ backup_file_path }}"
      register: backup_file_stat

    - name: Fail if backup file does not exist
      fail:
        msg: "Backup file does not exist at {{ backup_file_path }}"
      when: not backup_file_stat.stat.exists

    - name: Check backup file size
      debug:
        msg: "Backup file size: {{ backup_file_stat.stat.size }} bytes"

    - name: Validate backup file type (gzip check)
      command: file {{ backup_file_path }}
      register: file_type
      failed_when: "'gzip compressed data' not in file_type.stdout"

    - name: Extract the database backup
      shell: gunzip -c {{ backup_file_path }} > {{ db_restore_path }}
      register: extraction_result
      failed_when: extraction_result.rc != 0
      when: backup_file_stat.stat.exists

    - name: Debug extraction result
      debug:
        msg: "Backup file extracted: {{ db_restore_path }}"
      when: extraction_result.rc == 0

    - name: Restore the PostgreSQL database
      command: psql -U {{ db_user }} {{ db_name }} < {{ db_restore_path }}
      become_user: postgres
      environment:
        PGPASSWORD: redhat

    - name: Clean up local restored SQL file
      file:
        path: "{{ db_restore_path }}"
        state: absent
